### ISSUE TITLE
Inwonersaantallen niet correct

### ISSUE THREAD

**Issue by eddiewagt** [minvws/nl-covid19-data-backend-processing#3]
De aantallen inwoners zijn niet correct. De stand is van 1-1-2020, terwijl je voortschrijdend de juiste aantallen wil presenteren. Mijn advies is om de tabel 37230ned van het CBS te nemen waarin per maand de inwonersaantallen wordt bijgewerkt (inclusief de oorzaken van wijzigingen)

Wijziging: Tabel 03759ned van het CBS is ook een alternatief. Hierin kun je ook de leeftijden meenemen en eventueel een goed vergelijk gaan maken met de leeftijdsverdeling zoals in de landelijke casus wordt meegegeven.

Overigens ben ik benieuwd wat de RIVM nu hanteert als inwonersaantallen. Ik mag aannemen (en volgens mij heb ik dat wel gelezen) dat dit gebaseerd is op de data die vanuit het CBS wordt verstrekt.

**Comment by VWSCoronaDashboard7** [comment]
Dank voor de melding. We hebben reeds op de actielijst staan om de inwonersaantallen gelijk te trekken aan wat het RIVM gebruikt om verwarring in aantal tussen bron van de data (i.g.v. RIVM) en weergave op dashboard te voorkomen. We zullen dit issue updaten als dat is doorgevoerd.
