### ISSUE TITLE
The mortality graph is wrongly updated due to the change of the year

### ISSUE THREAD

**Issue by BeataSkuczynska** [minvws/nl-covid19-data-backend-processing#6]
The chart for the actual-predicted mortality on bottom of the [page](https://coronadashboard.government.nl/landelijk/sterfte) is incorrect for the week 28 December 2020 - 3 January 2021. The numbers presented are only for the the 4 days of 2020. I'm guessing this bug happened because [CBS](https://www.cbs.nl/nl-nl/cijfers/detail/70895ned) splitted the numbers for this week into two values: separetely for 2020 counterpart and separetly for 2021 counterpart.

**Comment by VWSCoronaDashboard7** [comment]
This has been corrected a while back but I missed the issue, thanks for the report.
