### ISSUE TITLE
Reported hospitalisations is not reflected correctly in the corresponding graph

### ISSUE THREAD

**Issue by great7ven** [minvws/nl-covid19-data-backend-processing#7]
### Describe the bug, issue or concern

Reported hospitalisations is not reflected correctly in the corresponding graph

### To Reproduce
1. Go to 'https://coronadashboard.rijksoverheid.nl/landelijk/ziekenhuis-opnames'
2. See error, in the left screen you see "ziekenhuisopnames" with a number (19-01-2021, 256), in the graph the day of yesterday is shown with the number 79, that's not even the number of "ziekenhuisopnames" of yesterday but it looks like the number of nursinghome care "verpleeghuiszorg". It's clearly not a correct number on the last shown day, the graph also feels not correct on the last day.

### Expected behavior
Show the correct number for the day in the graph..

### Screenshots
<img width="1920" alt="Screenshot_2021-01-19 Ziekenhuisopnames Dashboard Coronavirus Rijksoverheid nl" src="https://user-images.githubusercontent.com/20112266/105072189-da076500-5a85-11eb-9105-f04d78a13c2d.png">

**Desktop (please complete the following information):**
 - Win10
 - Firefox
 - Version 84.0.2

### Governance
- [v] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [v] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [v] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi, this type of question should really go to https://github.com/minvws/nl-covid19-data-dashboard since that is the repo dealing with the visualisations. About your question itself: we're showing different indicators there. One shows date of report (kpi + sidebar), the other the actual admission date. That's explained in the text above the graph which I advise you to carefully reread. Thanks for taking the time for reaching out!
